// Auto-generated by npm run generate:tests.
// Do not edit directly; update src/zapier-operation-ids.ts or src/api/index.json.

const App = require('../../src');

const operationFixtures = [
  {
    "operationId": "addCustomersToPool",
    "key": "add_customers_to_pool",
    "label": "Add Customers to Pool",
    "description": "Adds customers to a customer pool.",
    "method": "POST",
    "inputFields": [
      "projectId",
      "customerPoolId",
      "uniqueCustomerId",
      "emailId",
      "phoneNumber",
      "pushContactPoints",
      "name",
      "pinCode",
      "countryIsoCode",
      "timeZone"
    ],
    "inputData": {
      "customerPoolId": "customerPoolId value",
      "projectId": "projectId value",
      "uniqueCustomerId": "uniqueCustomerId-value",
      "emailId": "emailId-value",
      "phoneNumber": "phoneNumber-value",
      "pushContactPoints": [
        {
          "provider": "provider-value",
          "token": "token-value",
          "platform": "platform-value"
        }
      ],
      "name": "name-value",
      "pinCode": "pinCode-value",
      "countryIsoCode": "countryIsoCode-value",
      "timeZone": "timeZone-value"
    },
    "expectedUrl": "https://api.dokaai.com/v1/dokaai/customer/projects/projectId%20value/customer-pools/customerPoolId%20value/customers",
    "expectedAuthHeaders": {
      "x-client-key": "x-client-key-value",
      "x-client-secret": "x-client-secret-value"
    },
    "expectedBody": {
      "customerData": {
        "uniqueCustomerId": "uniqueCustomerId-value",
        "emailId": "emailId-value",
        "phoneNumber": "phoneNumber-value",
        "pushContactPoints": [
          {
            "provider": "provider-value",
            "token": "token-value",
            "platform": "platform-value"
          }
        ],
        "name": "name-value",
        "pinCode": "pinCode-value",
        "countryIsoCode": "countryIsoCode-value",
        "timeZone": "timeZone-value"
      }
    },
    "responseJson": {
      "status": "success",
      "data": {
        "customerId": "add_customers_to_pool-id"
      }
    },
    "expectedId": "add_customers_to_pool-id"
  },
  {
    "operationId": "addCustomerCustomAttribute",
    "key": "add_customer_custom_attribute",
    "label": "Create Customer Custom Attribute",
    "description": "Creates a customer custom attribute.",
    "method": "POST",
    "inputFields": [
      "projectId",
      "customerPoolId",
      "customAttributes"
    ],
    "inputData": {
      "customerPoolId": "customerPoolId value",
      "projectId": "projectId value",
      "customAttributes": [
        {
          "fieldName": "fieldName-value",
          "fieldDisplayName": "fieldDisplayName-value",
          "fieldDescription": "fieldDescription-value",
          "fieldType": "fieldType-value"
        }
      ]
    },
    "expectedUrl": "https://api.dokaai.com/v1/dokaai/customer/projects/projectId%20value/customer-pools/customerPoolId%20value/custom-attributes",
    "expectedAuthHeaders": {
      "x-client-key": "x-client-key-value",
      "x-client-secret": "x-client-secret-value"
    },
    "expectedBody": {
      "customAttributes": [
        {
          "fieldName": "fieldName-value",
          "fieldDisplayName": "fieldDisplayName-value",
          "fieldDescription": "fieldDescription-value",
          "fieldType": "fieldType-value"
        }
      ]
    },
    "responseJson": {
      "status": "success",
      "data": {}
    }
  },
  {
    "operationId": "associateCustomerToTargetAudienceList",
    "key": "associate_customer_to_target_audience_list",
    "label": "Add Customers to Target Audience List",
    "description": "Adds customers to a target audience list.",
    "method": "POST",
    "inputFields": [
      "projectId",
      "targetAudienceListId",
      "customerIds"
    ],
    "inputData": {
      "projectId": "projectId value",
      "targetAudienceListId": "targetAudienceListId value",
      "customerIds": [
        "customerIds-1",
        "customerIds-2"
      ]
    },
    "expectedUrl": "https://api.dokaai.com/v1/dokaai/nudge/projects/projectId%20value/target-audience-lists/targetAudienceListId%20value/customers",
    "expectedAuthHeaders": {
      "x-client-key": "x-client-key-value",
      "x-client-secret": "x-client-secret-value"
    },
    "expectedBody": {
      "customerIds": [
        "customerIds-1",
        "customerIds-2"
      ]
    },
    "responseJson": {
      "status": "success",
      "data": {
        "targetAudienceListId": "associate_customer_to_target_audience_list-id"
      }
    },
    "expectedId": "associate_customer_to_target_audience_list-id"
  },
  {
    "operationId": "deleteCustomerFromTargetAudienceList",
    "key": "delete_customer_from_target_audience_list",
    "label": "Remove Customer From Target Audience List",
    "description": "Removes a customer from a target audience list.",
    "method": "PATCH",
    "inputFields": [
      "projectId",
      "targetAudienceListId",
      "customerId"
    ],
    "inputData": {
      "targetAudienceListId": "targetAudienceListId value",
      "customerId": "customerId value",
      "projectId": "projectId value"
    },
    "expectedUrl": "https://api.dokaai.com/v1/dokaai/nudge/projects/projectId%20value/target-audience-lists/targetAudienceListId%20value/customer/customerId%20value",
    "expectedAuthHeaders": {
      "x-client-key": "x-client-key-value",
      "x-client-secret": "x-client-secret-value"
    },
    "responseJson": {
      "status": "success",
      "data": {
        "id": "delete_customer_from_target_audience_list-id"
      }
    },
    "expectedId": "delete_customer_from_target_audience_list-id"
  },
  {
    "operationId": "updateCustomerInPool",
    "key": "update_customer_in_pool",
    "label": "Update Customer in Pool",
    "description": "Updates a customer in a pool.",
    "method": "PUT",
    "inputFields": [
      "projectId",
      "customerPoolId",
      "customerId",
      "name",
      "countryIsoCode",
      "pushContactPoints",
      "emailId",
      "phoneNumber",
      "pinCode",
      "timeZone"
    ],
    "inputData": {
      "customerPoolId": "customerPoolId value",
      "customerId": "customerId value",
      "projectId": "projectId value",
      "name": "name-value",
      "countryIsoCode": "countryIsoCode-value",
      "pushContactPoints": [
        {
          "provider": "provider-value",
          "token": "token-value",
          "platform": "platform-value"
        }
      ],
      "emailId": "emailId-value",
      "phoneNumber": "phoneNumber-value",
      "pinCode": "pinCode-value",
      "timeZone": "timeZone-value"
    },
    "expectedUrl": "https://api.dokaai.com/v1/dokaai/customer/projects/projectId%20value/customer-pools/customerPoolId%20value/customers/customerId%20value",
    "expectedAuthHeaders": {
      "x-client-key": "x-client-key-value",
      "x-client-secret": "x-client-secret-value"
    },
    "expectedBody": {
      "name": "name-value",
      "countryIsoCode": "countryIsoCode-value",
      "pushContactPoints": [
        {
          "provider": "provider-value",
          "token": "token-value",
          "platform": "platform-value"
        }
      ],
      "emailId": "emailId-value",
      "phoneNumber": "phoneNumber-value",
      "pinCode": "pinCode-value",
      "timeZone": "timeZone-value"
    },
    "responseJson": {
      "status": "success",
      "data": {
        "id": "update_customer_in_pool-id"
      }
    },
    "expectedId": "update_customer_in_pool-id"
  },
  {
    "operationId": "removeCustomerFromPool",
    "key": "remove_customer_from_pool",
    "label": "Remove Customer From Pool",
    "description": "Removes a customer from a pool.",
    "method": "PATCH",
    "inputFields": [
      "projectId",
      "customerPoolId",
      "customerId"
    ],
    "inputData": {
      "customerPoolId": "customerPoolId value",
      "projectId": "projectId value",
      "customerId": "customerId value"
    },
    "expectedUrl": "https://api.dokaai.com/v1/dokaai/customer/projects/projectId%20value/customer-pools/customerPoolId%20value/customer/customerId%20value/status",
    "expectedAuthHeaders": {
      "x-client-key": "x-client-key-value",
      "x-client-secret": "x-client-secret-value"
    },
    "responseJson": {
      "status": "success",
      "data": {
        "id": "remove_customer_from_pool-id"
      }
    },
    "expectedId": "remove_customer_from_pool-id"
  },
  {
    "operationId": "triggerNotificationHandler",
    "key": "trigger_notification_handler",
    "label": "Send Notification",
    "description": "Sends a notification using a notification handler.",
    "method": "POST",
    "inputFields": [
      "projectId",
      "notificationHandlerId",
      "mode",
      "idempotencyKey"
    ],
    "inputData": {
      "projectId": "projectId value",
      "notificationHandlerId": "notificationHandlerId value",
      "mode": "mode-value",
      "idempotencyKey": "idempotencyKey-value"
    },
    "expectedUrl": "https://api.dokaai.com/v1/dokaai/nudge/projects/projectId%20value/notification-handlers/notificationHandlerId%20value/trigger",
    "expectedAuthHeaders": {
      "x-client-key": "x-client-key-value",
      "x-client-secret": "x-client-secret-value"
    },
    "expectedBody": {
      "mode": "mode-value",
      "idempotencyKey": "idempotencyKey-value"
    },
    "responseJson": {
      "status": "success",
      "data": {}
    }
  }
];
const searchFixtures = [
  {
    "operationId": "getPoolCustomers",
    "key": "get_pool_customers",
    "label": "Find Pool Customers",
    "description": "Finds customers in a pool.",
    "method": "GET",
    "inputFields": [
      "projectId",
      "customerPoolId",
      "search",
      "searchField",
      "filterOutTALId",
      "page",
      "size"
    ],
    "inputData": {
      "projectId": "projectId value",
      "customerPoolId": "customerPoolId value",
      "search": "search-value",
      "searchField": "searchField-value",
      "filterOutTALId": "filterOutTALId-value",
      "page": "page-value",
      "size": "size-value"
    },
    "expectedUrl": "https://api.dokaai.com/v1/dokaai/customer/projects/projectId%20value/customer-pools/customerPoolId%20value/customers",
    "expectedParams": {
      "search": "search-value",
      "searchField": "searchField-value",
      "filterOutTALId": "filterOutTALId-value",
      "page": "page-value",
      "size": "size-value"
    },
    "expectedAuthHeaders": {
      "x-client-key": "x-client-key-value",
      "x-client-secret": "x-client-secret-value"
    },
    "responseJson": {
      "status": "success",
      "data": [
        {
          "id": "get_pool_customers-id",
          "name": "get_pool_customers name"
        }
      ]
    },
    "expectedResult": [
      {
        "id": "get_pool_customers-id",
        "name": "get_pool_customers name"
      }
    ]
  },
  {
    "operationId": "getPoolCustomerById",
    "key": "get_pool_customer_by_id",
    "label": "Find Pool Customer by ID",
    "description": "Finds a customer in a pool by ID.",
    "method": "GET",
    "inputFields": [
      "projectId",
      "customerPoolId",
      "customerId",
      "attributeTypes"
    ],
    "inputData": {
      "projectId": "projectId value",
      "customerId": "customerId value",
      "customerPoolId": "customerPoolId value",
      "attributeTypes": "attributeTypes-value"
    },
    "expectedUrl": "https://api.dokaai.com/v1/dokaai/customer/projects/projectId%20value/customer-pools/customerPoolId%20value/customers/customerId%20value",
    "expectedParams": {
      "attributeTypes": "attributeTypes-value"
    },
    "expectedAuthHeaders": {
      "x-client-key": "x-client-key-value",
      "x-client-secret": "x-client-secret-value"
    },
    "responseJson": {
      "status": "success",
      "data": {
        "id": "get_pool_customer_by_id-id",
        "name": "get_pool_customer_by_id name"
      }
    },
    "expectedResult": [
      {
        "id": "get_pool_customer_by_id-id",
        "name": "get_pool_customer_by_id name"
      }
    ]
  },
  {
    "operationId": "getNotificationHandler",
    "key": "get_notification_handler",
    "label": "Find Notification Handler",
    "description": "Finds a notification handler by ID.",
    "method": "GET",
    "inputFields": [
      "projectId",
      "notificationHandlerId"
    ],
    "inputData": {
      "projectId": "projectId value",
      "notificationHandlerId": "notificationHandlerId value"
    },
    "expectedUrl": "https://api.dokaai.com/v1/dokaai/nudge/projects/projectId%20value/notification-handlers/notificationHandlerId%20value",
    "expectedAuthHeaders": {
      "x-client-key": "x-client-key-value",
      "x-client-secret": "x-client-secret-value"
    },
    "responseJson": {
      "status": "success",
      "data": {
        "id": "get_notification_handler-id",
        "name": "get_notification_handler name"
      }
    },
    "expectedResult": [
      {
        "id": "get_notification_handler-id",
        "name": "get_notification_handler name"
      }
    ]
  },
  {
    "operationId": "getAllNotificationHandlersInProject",
    "key": "get_all_notification_handlers_in_project",
    "label": "Find Notification Handlers",
    "description": "Finds notification handlers in the current project.",
    "method": "GET",
    "inputFields": [
      "projectId",
      "search",
      "page",
      "size"
    ],
    "inputData": {
      "projectId": "projectId value",
      "search": "search-value",
      "page": "page-value",
      "size": "size-value"
    },
    "expectedUrl": "https://api.dokaai.com/v1/dokaai/nudge/projects/projectId%20value/notification-handlers/",
    "expectedParams": {
      "search": "search-value",
      "page": "page-value",
      "size": "size-value"
    },
    "expectedAuthHeaders": {
      "x-client-key": "x-client-key-value",
      "x-client-secret": "x-client-secret-value"
    },
    "responseJson": {
      "status": "success",
      "data": [
        {
          "id": "get_all_notification_handlers_in_project-id",
          "name": "get_all_notification_handlers_in_project name"
        }
      ]
    },
    "expectedResult": [
      {
        "id": "get_all_notification_handlers_in_project-id",
        "name": "get_all_notification_handlers_in_project name"
      }
    ]
  },
  {
    "operationId": "getNotificationHandlerByKey",
    "key": "get_notification_handler_by_key",
    "label": "Find Notification Handler by Key",
    "description": "Finds a notification handler by its handler key.",
    "method": "GET",
    "inputFields": [
      "projectId",
      "handlerKey"
    ],
    "inputData": {
      "projectId": "projectId value",
      "handlerKey": "handlerKey value"
    },
    "expectedUrl": "https://api.dokaai.com/v1/dokaai/nudge/projects/projectId%20value/notification-handlers/key/handlerKey%20value",
    "expectedAuthHeaders": {
      "x-client-key": "x-client-key-value",
      "x-client-secret": "x-client-secret-value"
    },
    "responseJson": {
      "status": "success",
      "data": {
        "id": "get_notification_handler_by_key-id",
        "name": "get_notification_handler_by_key name"
      }
    },
    "expectedResult": [
      {
        "id": "get_notification_handler_by_key-id",
        "name": "get_notification_handler_by_key name"
      }
    ]
  }
];

const makeZ = (responseJson = { status: 'success', data: {} }) => {
  const requests = [];
  const z = {
    request: jest.fn(async (options) => {
      requests.push(options);
      return {
        json: responseJson,
        data: responseJson,
        throwForStatus: jest.fn(),
      };
    }),
  };

  return { z, requests };
};

const bundle = (inputData) => ({
  inputData,
  authData: {
    "x-client-key": "x-client-key-value",
    "x-client-secret": "x-client-secret-value"
},
});

describe('OpenAPI generated Zapier app', () => {
  it('builds selected creates from plain OpenAPI operationIds', () => {
    expect(Object.keys(App.creates)).toEqual(
      operationFixtures.map((fixture) => fixture.key),
    );

    for (const fixture of operationFixtures) {
      expect(App.creates[fixture.key].display.label).toBe(fixture.label);
      expect(App.creates[fixture.key].display.description).toBe(fixture.description);
      expect(App.creates[fixture.key].noun).toBe(fixture.label);
    }
  });

  it('builds selected searches from plain OpenAPI operationIds', () => {
    expect(Object.keys(App.searches)).toEqual(
      searchFixtures.map((fixture) => fixture.key),
    );

    for (const fixture of searchFixtures) {
      expect(App.searches[fixture.key].display.label).toBe(fixture.label);
      expect(App.searches[fixture.key].display.description).toBe(fixture.description);
      expect(App.searches[fixture.key].noun).toBe(fixture.label);
    }
  });

  it('derives auth fields from OpenAPI security schemes', () => {
    expect(App.authentication.fields.map((field) => field.key)).toEqual(
      [
      "x-client-key",
      "x-client-secret"
],
    );
  });

  it('validates auth against client secret metadata endpoint', async () => {
    const authResponse = {
      status: 'success',
      data: {
        workspaceId: '0XYR9WTB',
        name: 'test-zapier-key',
        environment: 'Production',
      },
    };
    const { z, requests } = makeZ(authResponse);

    const result = await App.authentication.test(z, bundle({}));

    expect(requests[0]).toMatchObject({
      method: 'GET',
      url: 'https://api.dokaai.com/v1/dokaai/opm/client-secrets/me',
      headers: {
        Accept: 'application/json',
        'x-client-key': 'x-client-key-value',
        'x-client-secret': 'x-client-secret-value',
      },
    });
    expect(result).toEqual(authResponse);
  });

  it('generates input fields from path params and request body schema', () => {
    for (const fixture of operationFixtures) {
      const fields = App.creates[fixture.key].operation.inputFields;

      expect(
        fields
          .filter((field) => typeof field === 'object')
          .map((field) => field.key),
      ).toEqual(fixture.inputFields);
    }
  });

  it('generates search input fields from path and query params', () => {
    for (const fixture of searchFixtures) {
      const fields = App.searches[fixture.key].operation.inputFields;

      expect(fields.map((field) => field.key)).toEqual(fixture.inputFields);
    }
  });

  it('performs each generated create using inferred OpenAPI request shape', async () => {
    for (const fixture of operationFixtures) {
      const { z, requests } = makeZ(fixture.responseJson);

      const result = await App.creates[fixture.key].operation.perform(
        z,
        bundle(fixture.inputData),
      );

      expect(requests[0].method).toBe(fixture.method);
      expect(requests[0].url).toBe(fixture.expectedUrl);
      expect(requests[0].params).toEqual(fixture.expectedParams);
      expect(requests[0].headers).toMatchObject({
        ...fixture.expectedAuthHeaders,
        ...(fixture.expectedBody === undefined
          ? {}
          : { 'Content-Type': 'application/json' }),
      });
      expect(requests[0].body).toEqual(fixture.expectedBody);

      if (fixture.expectedId !== undefined) {
        expect(result.id).toBe(fixture.expectedId);
      }
    }
  });

  it('performs each generated search using inferred OpenAPI request shape', async () => {
    for (const fixture of searchFixtures) {
      const { z, requests } = makeZ(fixture.responseJson);

      const result = await App.searches[fixture.key].operation.perform(
        z,
        bundle(fixture.inputData),
      );

      expect(requests[0].method).toBe(fixture.method);
      expect(requests[0].url).toBe(fixture.expectedUrl);
      expect(requests[0].params).toEqual(fixture.expectedParams);
      expect(requests[0].headers).toMatchObject(fixture.expectedAuthHeaders);
      expect(requests[0].body).toBeUndefined();
      expect(result).toEqual(fixture.expectedResult);
    }
  });
});
